### ISSUE TITLE
Build failing with M1 chip

### ISSUE THREAD

**Issue by SKYLARK-13** [KM8Oz/react-native-wireguard#7]
I am using this in my react-native app since long and building successfully in iMac with intel chip.
Recently I've upgraded to m1 mac and it is throwing the following error.

RN Version: 0.70.6

`FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:buildCMakeDebug[arm64-v8a]'.
> Build command failed.
  Error while executing process /Users/walkover/Library/Android/sdk/cmake/3.18.1/bin/ninja with arguments {-C /Users/walkover/Desktop/hello-mobile/android/app/.cxx/Debug/a572q66l/arm64-v8a dummy}
  ninja: Entering directory `/Users/walkover/Desktop/hello-mobile/android/app/.cxx/Debug/a572q66l/arm64-v8a'
  [1/3] Building wireguard-go
  FAILED: CMakeFiles/libwg-go.so 
  cd /Users/walkover/Desktop/hello-mobile/android/app/tools/libwg-go && make ANDROID_ARCH_NAME=arm64 ANDROID_C_COMPILER=/Users/walkover/Library/Android/sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang ANDROID_TOOLCHAIN_ROOT=/Users/walkover/Library/Android/sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/darwin-x86_64 ANDROID_LLVM_TRIPLE=aarch64-none-linux-android21 ANDROID_SYSROOT= ANDROID_PACKAGE_NAME= "CFLAGS=-g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security  -Wno-unused-command-line-argument" "LDFLAGS=-static-libstdc++ -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments  -fuse-ld=gold" DESTDIR=/Users/walkover/Desktop/hello-mobile/android/app/build/intermediates/cxx/Debug/a572q66l/obj/arm64-v8a BUILDDIR=/Users/walkover/Desktop/hello-mobile/android/app/build/intermediates/cxx/Debug/a572q66l/obj/arm64-v8a/../generated-src
  go get -tags linux || { chmod -fR +w "/Users/walkover/Desktop/hello-mobile/android/app/build/intermediates/cxx/Debug/a572q66l/obj/arm64-v8a/../generated-src/gopath/pkg/mod"; rm -rf "/Users/walkover/Desktop/hello-mobile/android/app/build/intermediates/cxx/Debug/a572q66l/obj/arm64-v8a/../generated-src/gopath/pkg/mod"; exit 1; }
  go: finding golang.org/x/sys v0.0.0-20190321052220-f7bb7a8bee54
  go: finding golang.zx2c4.com/wireguard v0.0.0-20190409083948-18fa27047265
  go: finding github.com/Microsoft/go-winio v0.4.12
  go: finding golang.org/x/net v0.0.0-20190320064053-1272bf9dcd53
  go: finding golang.org/x/crypto v0.0.0-20190320223903-b7391e95e576
  go: finding golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a
  go: finding golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
  go: finding golang.org/x/text v0.3.0
  go: downloading golang.zx2c4.com/wireguard v0.0.0-20190409083948-18fa27047265
  go: extracting golang.zx2c4.com/wireguard v0.0.0-20190409083948-18fa27047265
  go: downloading golang.org/x/sys v0.0.0-20190321052220-f7bb7a8bee54
  go: downloading golang.org/x/net v0.0.0-20190320064053-1272bf9dcd53
  go: downloading golang.org/x/crypto v0.0.0-20190320223903-b7391e95e576
  go: extracting golang.org/x/crypto v0.0.0-20190320223903-b7391e95e576
  go: extracting golang.org/x/net v0.0.0-20190320064053-1272bf9dcd53
  go: extracting golang.org/x/sys v0.0.0-20190321052220-f7bb7a8bee54
  # runtime/cgo
  clang-14: error: invalid linker name in argument '-fuse-ld=gold'
  make: *** [/Users/walkover/Desktop/hello-mobile/android/app/build/intermediates/cxx/Debug/a572q66l/obj/arm64-v8a/libwg-go.so] Error 1
  ninja: build stopped: subcommand failed.
  

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================`

**Comment by KM8Oz** [comment]
i think JDK version no compatible. u can use a striped version of expo to
avoid environment issues. I will add a working version as example soon

**Comment by SKYLARK-13** [comment]
I changed the linker in CMakeLists.txt as 'ld' from 'gold'
and downgraded the ndk version for ['os.arch'] == "aarch64" to 21.3.6528147 and it worked for me 🚀

**Comment by SKYLARK-13** [comment]
Issue resolved

**Comment by SKYLARK-13** [comment]
Issue resolved

**Comment by KM8Oz** [comment]
Thanks. I mistyped ndk there
